title: Alan Wong
# logo: /assets/img/logo.png
description: Hi! I'm Alan, an analyst/researcher in NYC focused on leveraging machine learning methods for business analytics and applied language research. I also dabble in creating tutorials and other educational resources.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
