title: Alan Wong
# logo: /assets/img/logo.png
description: Welcome to my personal page, where I post projects, tutorials, and other things.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
